#version 450
#define N 16
#define M 16

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout (binding = 0, r32f) uniform readonly image2D inputImage;
layout (binding = 1) buffer result {
  float isovist;
};

void main()
{
  float tmp = 0;
  for (int x = gl_GlobalInvocationID.x; x < gl_GlobalInvocationID.x+N; x++) {
    tmp += imageLoad(inputImage, ivec(x, gl_GlobalInvocationID.y*M));
  }
  atomicAdd(isovist, tmp);
}
