#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D resultImage;

void main()
{
  vec4 res = vec4(imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy)).rgb, 0.5);
	imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), res);
}
